### PR TITLE
Version 0.2.2 to 0.2.3

### PR DESCRIPTION
**Pull request by FrostionAAA**
Signed-off-by: FrostionAAA davidvcsandersen@hotmail.com

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Congrats on your first PR. As an owner of this map, you can click the merge button yourself if you would like. I can also click it for you too. Submitting changes via PR is generally a good thing to do, even when you can submit changes directly (thus good job).

It looks like line endings were swapped out. Not a problem. I'll look into adding a .gitattributes file. The problem is that other text editors, or other operating systems when they edit these same files may not insert the windows/DOS line endings. So we could wind up with a mix where some places look funky in notepad but not others.. It's not the end of the world.  I'll look to adding a .gitattributes that'll just deal with it.

Good to merge, no blockers i see.

**Comment by FrostionAAA** [comment]
Yes do add the .gitattributes file. There was no problem with th XML. I think it just looked different. I use CONText when editing.

**Comment by DanVanAtta** [comment]
Ah, it was xml formatting that was applied. That was another cleanup and would have made it look a lot different. That was also one-time.

**Comment by DanVanAtta** [comment]
If you saw everything on one line, then the .gitattributes file would help. Sounds like that was not the case in retrospect.

**Pull request merged**
